// This file is autogenerated by scripts/generate_page_data

export type ArticleMetadata = {
  title: string;
  url: string;
  category: string;
  tags: Array<string>;
  hidden?: boolean;
  postDate: string;
};

export type CategoryMetadata = {
  category: string;
  urls: Array<string>;
};

export type TagMetadata = {
  category: string;
  urls: Array<string>;
};

export const articleList = [
  {
    title: "Test Article's Are Cool",
    category: 'Testing',
    tags: ['tag1', 'tag2', 'tag3'],
    url: 'articles/post.svelte.md',
  },
];
export const catagoryList = [{ category: 'Testing', urls: ['articles/post.svelte.md'] }];
export const tagList = [{ tag: 'tag1' }, { tag: 'tag2' }, { tag: 'tag3' }];
